# Generated by Django 3.1.6 on 2021-02-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('passcode', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['userId'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSuccess', models.DateField(null=True)),
                ('lastUnsuccess', models.DateField(null=True)),
                ('visits', models.IntegerField(default=0)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
            options={
                'db_table': 'userlogininfo',
                'ordering': ['userId'],
            },
        ),
    ]
