# Generated by Django 3.1.6 on 2021-02-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='lastSuccess',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='lastUnsuccess',
            field=models.DateTimeField(null=True),
        ),
    ]
